baseURL = 'https://tadeodonegana.github.io/'
title = 'Tadeo Donegana'
theme = "PaperMod"

defaultContentLanguage = 'en'

publishDir = "docs"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "UA-123-45"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[languages.en]
contentDir = "content/en"
languageName = "English"
weight = 1
DateFormat = "January 2, 2006"

[[languages.en.menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 10

[[languages.en.menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20

[[languages.en.menu.main]]
identifier = "cv"
name = "LinkedIn"
url = "https://www.linkedin.com/in/tadeo-donegana-braunschweig/"
weight = 30

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Tadeo Donegana Braunschweig"
description = "Tadeo Donegana's blog"
keywords = [ "Blog", "Portfolio", "Tech", "Programming", "Tadeo Donegana", "Data Science", "Engineering" ]
author = "Tadeo Donegana Braunschweig"
images = [ "img/blog-header.png" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
disableSpecial1stPost = false
disableScrollToTop = false
displayFullLangName = true
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

  [params.assets]
  favicon = "img/favicon.ico"
  apple_touch_icon = "<link / abs url>"
  safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "Home"

  [params.homeInfoParams]
  Title = "Hello World 👋"
  Content = "My name is *Tadeo Donegana Braunschweig* and I am a B.S. in Artificial Intelligence student at the [University of Palermo](https://www.palermo.edu/). In this blog you will find posts about some stuff I am currently learning and some projects i have developed. I really enjoy meeting new people, feel free to  email me to tadeodonegana[at]gmail[dot]com."

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/tadeodonegana"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/tadeo-donegana-braunschweig/"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/tadeodonegana"

  [[params.socialIcons]]
  name = "email"
  url = "mailto:tadeodonegana@gmail.com"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.editPost]
  URL = "https://github.com/tadeodonegana/tadeodonegana.github.io/tree/main/content"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]